### ISSUE TITLE
Build fails with Go 1.23 because of changed testing.testDeps

### ISSUE THREAD

**Issue by stefanb** [hofstadter-io/hof#391]
When trying to build with Go 1.23 rc1 in
* https://github.com/Homebrew/homebrew-core/pull/175310

It failed at
https://github.com/hofstadter-io/hof/blob/bebc58f867e4341e3060f2421910acef6b743ea5/script/runtime/exe_next.go#L52

with [error](https://github.com/Homebrew/homebrew-core/actions/runs/9617673150/job/26535459459?pr=175310#step:3:10846):
````
  # github.com/hofstadter-io/hof/script/runtime
  script/runtime/exe_next.go:52:26: cannot use nopTestDeps{} (value of type nopTestDeps) as testing.testDeps value in argument to testing.MainStart: nopTestDeps does not implement testing.testDeps (missing method InitRuntimeCoverage)
````

`InitRuntimeCoverage` was added by @rsc in:
https://github.com/golang/go/commit/180ea45566d19e60aa2d660f6139b7f6e18ff56b#diff-36f401ff1ffadb7d7a39cf41c2329615b159fa95cf2e14c1f58d8c46331af429R208

See
* https://github.com/golang/go/issues/67401
* https://tip.golang.org/doc/go1.23#linker
* https://github.com/golang/go/blob/82c14346d89ec0eeca114f9ca0e88516b2cda454/src/testing/internal/testdeps/deps.go#L218-L223

Given the NOP nature of `nopTestDeps` a possible workaround could be to just implement a dummy/nop function `InitRuntimeCoverage()` in the `nopTestDeps`:
````go
func (nopTestDeps) InitRuntimeCoverage() (mode string, tearDown func(string, string) (string, error), snapcov func() float64) {
	return
}
````

**Comment by verdverm** [comment]
Living on the edge eh?! Thanks for the heads up and initial investigation

We've seen this before, it's one area where Go is not API stable :[

I can probably roll over the old/new exe files and the build directives therein

- https://github.com/hofstadter-io/hof/blob/_dev/script/runtime/exe_next.go#L5
- https://github.com/hofstadter-io/hof/blob/_dev/script/runtime/exe_old.go#L5

**Comment by verdverm** [comment]
@stefanb please let me know if `_dev` branch (our main branch) works for you now

I'm going to look at updating CUE to 0.9.1+ or maybe a 0.10.0-beta/rc and then cut a new version

**Comment by stefanb** [comment]
@verdverm the most i could (quickly) test is if it builds or run some unit tests, not all the functionality in practice. Would that really be enough?

**Comment by verdverm** [comment]
yeah, just whatever is failing for you. I find it unlikely this changed any behavior you rely on, unless you are using the hidden `hof run` command (which is based on the `testscript` package both Go & CUE use, but exposed as a scripting language)

**Comment by stefanb** [comment]
Still needs a release > `v0.6.9` that includes fix from https://github.com/hofstadter-io/hof/pull/392, see: https://github.com/hofstadter-io/hof/releases

**Comment by verdverm** [comment]
@stefanb just cut a new release candidate
