### PR TITLE
cmd/run: fix testing package usage for changes to API in go1.23

### LINKED ISSUE #391: Build fails with Go 1.23 because of changed testing.testDeps
When trying to build with Go 1.23 rc1 in
* https://github.com/Homebrew/homebrew-core/pull/175310

It failed at
https://github.com/hofstadter-io/hof/blob/bebc58f867e4341e3060f2421910acef6b743ea5/script/runtime/exe_next.go#L52

with [error](https://github.com/Homebrew/homebrew-core/actions/runs/9617673150/job/26535459459?pr=175310#step:3:10846):
````
  # github.com/hofstadter-io/hof/script/runtime
  script/runtime/exe_next.go:52:26: cannot use nopTestDeps{} (value of type nopTestDeps) as testing.testDeps value in argument to testing.MainStart: nopTestDeps does not implement testing.testDeps (missing method InitRuntimeCoverage)
````

`InitRuntimeCoverage` was added by @rsc in:
https://github.com/golang/go/commit/180ea45566d19e60aa2d660f6139b7f6e18ff56b#diff-36f401ff1ffadb7d7a39cf41c2329615b159fa95cf2e14c1f58d8c46331af429R208

See
* https://github.com/golang/go/issues/67401
* https://tip.golang.org/doc/go1.23#linker
* https://github.com/golang/go/blob/82c14346d89ec0eeca114f9ca0e88516b2cda454/src/testing/internal/testdeps/deps.go#L218-L223

Given the NOP nature of `nopTestDeps` a possible workaround could be to just implement a dummy/nop function `InitRuntimeCoverage()` in the `nopTestDeps`:
````go
func (nopTestDeps) InitRuntimeCoverage() (mode string, tearDown func(string, string) (string, error), snapcov func() float64) {
	return
}
````

### PR DESCRIPTION
**Pull request by verdverm**
Fixes #391

### CODE REVIEW

**Comment by stefanb** [comment]
This still needs to be included in a release.

**Comment by verdverm** [comment]
@stefanb Sounds like CUE is going to cut a new release just after Go cuts 1.23, at which point we will plan to cut a new release of hof

**Comment by stefanb** [comment]
FYI, Go 1.23 was released a few days ago, maybe it is a good time for a release 😉
